version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    expose:
      - "3000"
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    container_name: frontend-container
    expose:
      - "3000"
    depends_on:
      - mysql
      - backend
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
